# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  boot.initrd = {
    availableKernelModules = ["nvme" "xhci_pci" "usb_storage" "usbhid" "sd_mod" "sdhci_pci"];
    kernelModules = [];
    systemd.enable = true;
    luks.fido2Support = false;
    luks.devices = {
      cryptroot = {
        # allowDiscards = true;
        device = "/dev/disk/by-partlabel/cryptroot";
        crypttabExtraOpts = ["fido2-device=auto"];
      };
      crypt_ssd1 = {
        # allowDiscards = true;
        device = "/dev/disk/by-id/ata-Samsung_SSD_870_QVO_8TB_S5SSNF0WA10922R";
        crypttabExtraOpts = ["fido2-device=auto"];
      };
    };
  };


  fileSystems."/" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = ["subvol=@root" "noatime" "nodiratime" "compress=zstd"];
  };

  fileSystems."/nix" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = ["subvol=@nix" "noatime" "nodiratime" "compress=zstd"];
  };

  # Big, disposable-but-persistent data lives here — the single exception to
  # the "persistent state lives on /data" policy. @persist is a dedicated
  # subvol on the host NVMe: it survives the @root rollback (so it persists
  # across reboots), but it is NOT backed up the way /data is, because its
  # contents are large and freely re-downloadable. Consumers point straight at
  # subdirs (no symlinks):
  #   /persist/monero — the Monero blockchain (~200 GB), via services.monero.dataDir
  #   /persist/ai     — local AI models / caches, via /data/ai/flake.nix
  # Adding a new big consumer = just `mkdir /persist/<name>`; no new subvol.
  fileSystems."/persist" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = ["subvol=@persist" "noatime" "nodiratime" "compress=zstd"];
  };

  # Subvol that holds the swapfile. No compression here so swap pages
  # map 1:1 to disk; NOCOW is applied to the swapfile itself by NixOS's
  # swapDevices module.
  fileSystems."/var/swap" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = ["subvol=@swap" "noatime"];
  };

  fileSystems."/boot" = {
    # vfat filesystem label set at install time: `mkfs.vfat -n BOOT …`.
    device = "/dev/disk/by-label/BOOT";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  swapDevices = [
    {
      device = "/var/swap/swapfile";
      size = 16 * 1024; # 16 GiB
    }
  ];

  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.npu.enable = true;
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
