# Edit this configuration file to define what should be installed on
# your system.  Help is available in the configuration.nix(5) man page
# and in the NixOS manual (accessible by running ‘nixos-help’).

{ config, pkgs, lib, inputs, ... }:

{
  imports = [ ./hardware-configuration.nix ];
  kirk.nixosScripts = {
    enable = true;
    configDir = "/data";
    machine = "deck-oled";
  };

  # Bootloader.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  boot.initrd.luks.devices."luks-e5917c4f-0f75-40e7-bce3-55328c2c5cea".device = "/dev/disk/by-uuid/e5917c4f-0f75-40e7-bce3-55328c2c5cea";
  networking.hostName = "deck-oled"; # Define your hostname.

  # Enable networking
  networking.networkmanager.enable = true;

  # Set your time zone.
  time.timeZone = "Europe/Copenhagen";
  i18n.defaultLocale = "en_DK.UTF-8";
  i18n.extraLocaleSettings = {
    LC_ADDRESS = "da_DK.UTF-8";
    LC_IDENTIFICATION = "da_DK.UTF-8";
    LC_MEASUREMENT = "da_DK.UTF-8";
    LC_MONETARY = "da_DK.UTF-8";
    LC_NAME = "da_DK.UTF-8";
    LC_NUMERIC = "da_DK.UTF-8";
    LC_PAPER = "da_DK.UTF-8";
    LC_TELEPHONE = "da_DK.UTF-8";
    LC_TIME = "da_DK.UTF-8";
  };

  nix = {
    package = pkgs.nixVersions.latest;
    settings = {
      experimental-features = ["nix-command" "flakes"];
      download-buffer-size = 500000000; # 500 MB
      # Faster builds
      cores = 0;
      # Return more information when errors happen
      show-trace = true;
    };
    # Use the pinned nixpkgs version that is already used, when using `nix shell nixpkgs#package`
    registry.nixpkgs = {
      from = {
        id = "nixpkgs";
        type = "indirect";
      };
      flake = inputs.nixpkgs;
    };
  };

  # Enable the X11 windowing system.
  services.xserver.enable = true;

  # Enable the Cinnamon Desktop Environment.
  # services.displayManager.cosmic-greeter.enable = true;
  services.desktopManager.cosmic.enable = true;
  services.gnome.gnome-keyring.enable = false;
  services.gnome.gcr-ssh-agent.enable = false;
  # services.displayManager.autoLogin = {
  #   enable = true;
  #   user = "user";
  # };

  jovian = {
    devices.steamdeck.enable = true;
    steamos.useSteamOSConfig = true;
    steam = {
      enable = true;
      autoStart = true;
      desktopSession = "cosmic";
      user = "user";
    };
    hardware.has.amd.gpu = true;
  };
  hardware.enableRedistributableFirmware = true;

  programs.ssh.startAgent = true;

  services.xserver.xkb = {
    layout = "rk";
    extraLayouts.rk = {
      description = "rk - Custom KLFC layout";
      languages = [ "eng" ];
      symbolsFile = "${inputs.keyboard-layout.packages.${pkgs.system}.rk}/symbols/rk";
      typesFile = "${inputs.keyboard-layout.packages.${pkgs.system}.rk}/types/rk";
    };
  };

  # services.xserver.exportConfiguration = true;

  environment.sessionVariables.XKB_CONFIG_ROOT = lib.mkForce (let
    klfcPatcher = pkgs.writeShellApplication {
      name = "klfc-patcher";
      runtimeInputs = with pkgs; [ gnugrep gawk coreutils ];
      text = ''
        add_line_under_header () {
          file=$1
          header=$2
          line=$3
          
          header_with_comment="$header"$'\t'"// Generated by KLFC"
          line_with_comment="$line"$'\t'"// Generated by KLFC"
          lines="$line"$'\n'"$line_with_comment"

          if grep -qFx "$lines" "$file"; then
            return
          fi

          if grep -qFx "$header_with_comment" "$file"; then
            awk -v header="$header_with_comment" -v line="$line_with_comment" '
              { print }
              { if ($0 == header) { print line } }
            ' "$file" > "$file.tmp"
            mv "$file.tmp" "$file"
          else
            printf "\n%s\n%s\n" "$header_with_comment" "$line_with_comment" >> "$file"
          fi
        }

        add_type () {
          file=$1
          layout=$2

          for group in 0 1 2 3 4; do
            if [ "$group" -eq 0 ]; then
              header=$'! layout\t=\ttypes'
              line=$'  '"$layout"$'\t=\t+'"$layout"
            else
              header=$'! layout['"$group"$']\t=\ttypes'
              line=$'  '"$layout"$'\t=\t+'"$layout:$group"
            fi

            add_line_under_header "$file" "$header" "$line"
          done
        }

        out_dir=$1
        layout_name=$2

        add_type "$out_dir/rules/base" "$layout_name"
        add_type "$out_dir/rules/evdev" "$layout_name"
      '';
    };

    # Grab the generated XKB directory directly from the NixOS option
    nixosXkbDir = config.services.xserver.xkb.dir;
    
  in pkgs.runCommand "xkb-rk-patched" {} ''
    cp -rL ${nixosXkbDir} $out
    chmod -R u+w $out

    ${pkgs.lib.getExe klfcPatcher} $out "rk"
  '');

  # Enable CUPS to print documents.
  services.printing.enable = true;

  # Enable sound with pipewire.
  services.pulseaudio.enable = false;
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
    # If you want to use JACK applications, uncomment this
    #jack.enable = true;

    # use the example session manager (no others are packaged yet so this is enabled by default,
    # no need to redefine it in your config for now)
    #media-session.enable = true;
  };

  # Enable touchpad support (enabled default in most desktopManager).
  # services.xserver.libinput.enable = true;

  # Define a user account. Don't forget to set a password with ‘passwd’.
  users.users.user = {
    isNormalUser = true;
    description = "Rasmus Kirk";
    extraGroups = [ "networkmanager" "wheel" ];
    packages = with pkgs; [
    #  thunderbird
    ];
  };

  # Install firefox.
  programs.firefox.enable = true;

  # Allow unfree packages
  nixpkgs.config.allowUnfree = true;

  # List packages installed in system profile. To search, run:
  # $ nix search wget
  environment.systemPackages = with pkgs; [
  #  vim # Do not forget to add an editor to edit configuration.nix! The Nano editor is also installed by default.
  #  wget
  ];

  security.sudo.extraConfig = ''
    Defaults timestamp_timeout=60
  '';

  # Some programs need SUID wrappers, can be configured further or are
  # started in user sessions.
  # programs.mtr.enable = true;
  # programs.gnupg.agent = {
  #   enable = true;
  #   enableSSHSupport = true;
  # };

  # List services that you want to enable:

  # Enable the OpenSSH daemon.
  # services.openssh.enable = true;

  # Open ports in the firewall.
  # networking.firewall.allowedTCPPorts = [ ... ];
  # networking.firewall.allowedUDPPorts = [ ... ];
  # Or disable the firewall altogether.
  # networking.firewall.enable = false;

  # This value determines the NixOS release from which the default
  # settings for stateful data, like file locations and database versions
  # on your system were taken. It‘s perfectly fine and recommended to leave
  # this value at the release version of the first install of this system.
  # Before changing this value read the documentation for this option
  # (e.g. man configuration.nix or on https://nixos.org/nixos/options.html).
  system.stateVersion = "25.11"; # Did you read the comment?
}
