# Custom klfc-compiled XKB keyboard layout. klfc emits symbols/<name> and
# types/<name>, but the custom key *types* aren't registered in xkb's
# rules/base + rules/evdev, so XKB ignores them. The patcher below copies the
# system xkb dir, injects the `+<layout>` type lines under the right headers,
# and points XKB_CONFIG_ROOT at the patched copy. Extracted from the per-machine
# blocks in the deck-oled / work configs.
{
  config,
  pkgs,
  lib,
  ...
}:
with lib; let
  cfg = config.kirk.keyboardLayout;

  klfcPatcher = pkgs.writeShellApplication {
    name = "klfc-patcher";
    runtimeInputs = with pkgs; [gnugrep gawk coreutils];
    inheritPath = false;
    text = ''
      add_line_under_header () {
        file=$1
        header=$2
        line=$3

        header_with_comment="$header"$'\t'"// Generated by KLFC"
        line_with_comment="$line"$'\t'"// Generated by KLFC"
        lines="$line"$'\n'"$line_with_comment"

        if grep -qFx "$lines" "$file"; then
          return
        fi

        if grep -qFx "$header_with_comment" "$file"; then
          awk -v header="$header_with_comment" -v line="$line_with_comment" '
            { print }
            { if ($0 == header) { print line } }
          ' "$file" > "$file.tmp"
          mv "$file.tmp" "$file"
        else
          printf "\n%s\n%s\n" "$header_with_comment" "$line_with_comment" >> "$file"
        fi
      }

      add_type () {
        file=$1
        layout=$2

        for group in 0 1 2 3 4; do
          if [ "$group" -eq 0 ]; then
            header=$'! layout\t=\ttypes'
            line=$'  '"$layout"$'\t=\t+'"$layout"
          else
            header=$'! layout['"$group"$']\t=\ttypes'
            line=$'  '"$layout"$'\t=\t+'"$layout:$group"
          fi

          add_line_under_header "$file" "$header" "$line"
        done
      }

      out_dir=$1
      layout_name=$2

      add_type "$out_dir/rules/base" "$layout_name"
      add_type "$out_dir/rules/evdev" "$layout_name"
    '';
  };
in {
  options.kirk.keyboardLayout = {
    enable = mkEnableOption "custom klfc-compiled XKB keyboard layout";

    layout = mkOption {
      type = types.str;
      default = "rk";
      description = "Layout name; must match a symbols/<name> and types/<name> in `package`.";
    };

    package = mkOption {
      type = types.package;
      example = literalExpression "inputs.keyboard-layout.packages.\${pkgs.system}.rk";
      description = "klfc-built layout package providing symbols/<layout> and types/<layout>.";
    };

    description = mkOption {
      type = types.str;
      default = "Custom KLFC layout";
      description = "Human-readable layout description for xkb.extraLayouts.";
    };

    languages = mkOption {
      type = types.listOf types.str;
      default = ["eng"];
      description = "Languages declared for the layout in xkb.extraLayouts.";
    };
  };

  config = mkIf cfg.enable {
    services.xserver.xkb = {
      layout = cfg.layout;
      extraLayouts.${cfg.layout} = {
        inherit (cfg) description languages;
        symbolsFile = "${cfg.package}/symbols/${cfg.layout}";
        typesFile = "${cfg.package}/types/${cfg.layout}";
      };
    };

    # Patch the xkb rules so the klfc-generated key types are actually picked up.
    environment.sessionVariables.XKB_CONFIG_ROOT = mkForce (
      pkgs.runCommand "xkb-${cfg.layout}-patched" {} ''
        cp -rL ${config.services.xserver.xkb.dir} $out
        chmod -R u+w $out

        ${getExe klfcPatcher} $out "${cfg.layout}"
      ''
    );
  };
}
