# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "thunderbolt" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  # Root LUKS — passphrase prompted at console in initrd.
  # Referenced by GPT partition label set at install time: `sgdisk -c 2:cryptroot`.
  boot.initrd.luks.devices.cryptroot = {
    device = "/dev/disk/by-partlabel/cryptroot";
    allowDiscards = true;
  };

  fileSystems."/" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = ["subvol=@root" "noatime" "nodiratime" "compress=zstd"];
  };

  fileSystems."/nix" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = ["subvol=@nix" "noatime" "nodiratime" "compress=zstd"];
  };

  # Exception to the "persistent state lives on /data" policy:
  # the Monero blockchain (~200 GB and growing) lives on the host NVMe
  # so it doesn't unbalance /data's 8 TB SSD usage.
  fileSystems."/var/lib/monero" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = ["subvol=@monero" "noatime" "nodiratime" "compress=zstd"];
  };

  # Subvol that holds the swapfile. No compression here so swap pages
  # map 1:1 to disk; NOCOW is applied to the swapfile itself by NixOS's
  # swapDevices module.
  fileSystems."/var/swap" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = ["subvol=@swap" "noatime"];
  };

  fileSystems."/boot" = {
    # vfat filesystem label set at install time: `mkfs.vfat -n BOOT …`.
    device = "/dev/disk/by-label/BOOT";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  swapDevices = [
    {
      device = "/var/swap/swapfile";
      size = 16 * 1024; # 16 GiB
    }
  ];

  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.npu.enable = true;
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
